pipeline {
    agent any

    tools {
        nodejs "NodeJS"
    }


    environment {
        CI = 'true'
        HOME = '.'
        npm_config_cache = 'npm-cache'
        aws_credential = "AWS_CREDENTIAL_ID"
        bucket = "todo-app-js"
        region = "us-east-2"
    }
    stages {
        stage('Build') {
            steps {
                cd 'todo-app'
                sh 'npm install'
                sh 'npm run build'
            }
        }
        stage('Production') {
            steps {
                withAWS(region:'${region}',credentials:'${aws_credential}') {
                    s3Delete(bucket: '${bucket}', path:'**/*')
                    s3Upload(bucket: '${bucket}', workingDir:'build', includePathPattern:'**/*');
                }
            }
        }
    }
}