pipeline {
    agent any

    tools {
        nodejs "NodeJS"
    }


    environment {
        CI = 'false'
        HOME = '.'
        npm_config_cache = 'npm-cache'
    }
    stages {
        stage('Build') {
            steps {
                dir('todo-app') {
                    sh 'npm install'
                    sh 'npm run build'
                }
            }
        }
        stage('Production') {
            steps {
                withAWS(region:'us-east-2',credentials:'AWS_CREDENTIAL_ID') {
                    s3Delete(bucket: 'todo-app-js', path:'**/*')
                    s3Upload(bucket: 'todo-app-js', workingDir:'build', includePathPattern:'**/*');
                }
            }
        }
    }
}